name = "PlutoDependencyExplorer"
uuid = "b830bcf7-2908-40eb-83e1-a82d87062ab2"
license = "MIT"
authors = ["Paul Berg <paul@plutojl.org>", "Fons van der Plas <fons@plutojl.org>", "Stephan Sahm <stephan.sahm@jolin.io>"]
version = "1.0.401"

[deps]
ExpressionExplorer = "27279169-5e6b-450a-a298-ff8b56ddcd23"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
ExpressionExplorer = "0.6, 1"
InteractiveUtils = "1"
Markdown = "1"
julia = "1.6"
